name: Feature request
description: Make a feature request
title: "[FEAT] <title>"
labels: enhancement
assignees:
  - hsloot
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill this feature request!
  - type: checkboxes
    id: terms
    attributes:
      label: Submission terms and conditions
      options:
        - label: |
            I aggree to follow the [Code of Conduct](https://github.com/hsloot/integratecpp/blob/main/.github/CODE_OF_CONDUCT.md) that this repository adheres to.
          required: true
        - label: |
            I checked the [current issues](https://github.com/hsloot/integratecpp/issues) for duplicate problems.
          required: true
  - type: textarea
    id: report
    attributes:
      label: Feature request
      description:
        Please briefly describe your feature request. Consider including suggestions how to implemented **after a brief summary**.
    validations:
      required: true
