# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

integration_error <- function(what = NULL) {
    .Call(`_integratecpp_integration_error`, what)
}

max_subdivision_error <- function(what = NULL) {
    .Call(`_integratecpp_max_subdivision_error`, what)
}

roundoff_error <- function(what = NULL) {
    .Call(`_integratecpp_roundoff_error`, what)
}

bad_integrand_error <- function(what = NULL) {
    .Call(`_integratecpp_bad_integrand_error`, what)
}

extrapolation_roundoff_error <- function(what = NULL) {
    .Call(`_integratecpp_extrapolation_roundoff_error`, what)
}

divergence_error <- function(what = NULL) {
    .Call(`_integratecpp_divergence_error`, what)
}

invalid_input_error <- function(what = NULL) {
    .Call(`_integratecpp_invalid_input_error`, what)
}

Rcpp_integrate <- function(fn, lower, upper, subdivisions, epsrel, epsabs) {
    .Call(`_integratecpp_Rcpp_integrate`, fn, lower, upper, subdivisions, epsrel, epsabs)
}

