# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

integration_logic_error <- function(what) {
    .Call(`_integratecpp_integration_logic_error`, what)
}

integration_runtime_error <- function(what) {
    .Call(`_integratecpp_integration_runtime_error`, what)
}

max_subdivision_error <- function(what) {
    .Call(`_integratecpp_max_subdivision_error`, what)
}

roundoff_error <- function(what) {
    .Call(`_integratecpp_roundoff_error`, what)
}

bad_integrand_error <- function(what) {
    .Call(`_integratecpp_bad_integrand_error`, what)
}

extrapolation_roundoff_error <- function(what) {
    .Call(`_integratecpp_extrapolation_roundoff_error`, what)
}

divergence_error <- function(what) {
    .Call(`_integratecpp_divergence_error`, what)
}

invalid_input_error <- function(what) {
    .Call(`_integratecpp_invalid_input_error`, what)
}

Rcpp_integrate <- function(fn, lower, upper, subdivisions, epsrel, epsabs, lenw) {
    .Call(`_integratecpp_Rcpp_integrate`, fn, lower, upper, subdivisions, epsrel, epsabs, lenw)
}

integrator__new <- function(limit, epsrel, epsabs, lenw) {
    .Call(`_integratecpp_integrator__new`, limit, epsrel, epsabs, lenw)
}

integrator__get_limit <- function(ptr) {
    .Call(`_integratecpp_integrator__get_limit`, ptr)
}

integrator__set_limit <- function(ptr, limit) {
    invisible(.Call(`_integratecpp_integrator__set_limit`, ptr, limit))
}

integrator__get_epsrel <- function(ptr) {
    .Call(`_integratecpp_integrator__get_epsrel`, ptr)
}

integrator__set_epsrel <- function(ptr, epsrel) {
    invisible(.Call(`_integratecpp_integrator__set_epsrel`, ptr, epsrel))
}

integrator__get_epsabs <- function(ptr) {
    .Call(`_integratecpp_integrator__get_epsabs`, ptr)
}

integrator__set_epsabs <- function(ptr, epsabs) {
    invisible(.Call(`_integratecpp_integrator__set_epsabs`, ptr, epsabs))
}

integrator__get_lenw <- function(ptr) {
    .Call(`_integratecpp_integrator__get_lenw`, ptr)
}

integrator__set_lenw <- function(ptr, lenw) {
    invisible(.Call(`_integratecpp_integrator__set_lenw`, ptr, lenw))
}

integrator__integrate <- function(ptr, fn, lower, upper) {
    .Call(`_integratecpp_integrator__integrate`, ptr, fn, lower, upper)
}

