# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
#
# NOTE: This workflow is overkill for most R packages and
# check-standard.yaml is likely a better choice.
# usethis::use_github_action("check-standard") will install it.
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: check-full

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macOS-latest,   r: 'release'}

          - {os: windows-latest, r: 'release'}
          # Don't test on Windows + R<4.0 due to missing C++17 support of Rtools35
          # Use 4.0 to trigger usage of Rtools40
          - {os: windows-latest, r: '4.0'}

          # Use older ubuntu to maximise backward compatibility
          - {os: ubuntu-18.04,   r: 'devel', http-user-agent: 'release'}
          - {os: ubuntu-18.04,   r: 'release'}
          - {os: ubuntu-18.04,   r: 'oldrel-1'}
          - {os: ubuntu-18.04,   r: 'oldrel-2'}
          - {os: ubuntu-18.04,   r: 'oldrel-3'}
          - {os: ubuntu-18.04,   r: 'oldrel-4'}
          - {os: ubuntu-18.04,   r: 'release',  cxx_std: 'C++14'}
          - {os: ubuntu-18.04,   r: 'release',  cxx_std: 'C++17'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - if: ${{ matrix.config.cxx_std }}
        name: use CXX_STD = ${{ matrix.config.cxx_std }}
        run:  |
          cxx_std <- "${{ matrix.config.cxx_std }}"
          file <- file.path("DESCRIPTION")
          readLines(file) |>
              sapply(
                  function(x)
                      gsub(
                          "(?<=SystemRequirements:[[:space:]])C\\+\\+11",
                          cxx_std,
                          x,
                          perl = TRUE)) |>
              writeLines(file)
          cxx_std <- gsub("[\\+]{2}", "XX", cxx_std)
          file <- file.path("src", "Makevars")
          readLines(file) |>
              sapply(
                  function(x)
                      gsub(
                          "(?<=CXX_STD[[:space:]]=[[:space:]])CXX11",
                          cxx_std,
                          x,
                          perl = TRUE)) |>
              writeLines(file)
        shell: Rscript {0}

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
