on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: run-rchk

jobs:
  rchk:
    runs-on: ubuntu-latest
    container:
      image: rhub/ubuntu-rchk
      options: --user=root
    steps:
    - uses: actions/checkout@v2
    - uses: r-lib/actions/run-rchk@v2
