# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Rcpp__integration_logic_error__catch_what <- function(what) {
    .Call(`_testutils_integratecpp_Rcpp__integration_logic_error__catch_what`, what)
}

Rcpp__integration_runtime_error__catch_what <- function(what) {
    .Call(`_testutils_integratecpp_Rcpp__integration_runtime_error__catch_what`, what)
}

Rcpp__max_subdivision_error__catch_what <- function(what) {
    .Call(`_testutils_integratecpp_Rcpp__max_subdivision_error__catch_what`, what)
}

Rcpp__roundoff_error__catch_what <- function(what) {
    .Call(`_testutils_integratecpp_Rcpp__roundoff_error__catch_what`, what)
}

Rcpp__bad_integrand_error__catch_what <- function(what) {
    .Call(`_testutils_integratecpp_Rcpp__bad_integrand_error__catch_what`, what)
}

Rcpp__extrapolation_roundoff_error__catch_what <- function(what) {
    .Call(`_testutils_integratecpp_Rcpp__extrapolation_roundoff_error__catch_what`, what)
}

Rcpp__divergence_error__catch_what <- function(what) {
    .Call(`_testutils_integratecpp_Rcpp__divergence_error__catch_what`, what)
}

Rcpp__invalid_input_error__catch_what <- function(what) {
    .Call(`_testutils_integratecpp_Rcpp__invalid_input_error__catch_what`, what)
}

Rcpp__integrate <- function(fn, lower, upper, max_subdivisions, relative_accuracy, absolute_accuracy, work_size) {
    .Call(`_testutils_integratecpp_Rcpp__integrate`, fn, lower, upper, max_subdivisions, relative_accuracy, absolute_accuracy, work_size)
}

Rcpp__integrator__new <- function(max_subdivisions, relative_accuracy, absolute_accuracy, work_size) {
    .Call(`_testutils_integratecpp_Rcpp__integrator__new`, max_subdivisions, relative_accuracy, absolute_accuracy, work_size)
}

Rcpp__integrator__get_max_subdivisions <- function(ptr) {
    .Call(`_testutils_integratecpp_Rcpp__integrator__get_max_subdivisions`, ptr)
}

Rcpp__integrator__set_max_subdivisions <- function(ptr, max_subdivisions) {
    invisible(.Call(`_testutils_integratecpp_Rcpp__integrator__set_max_subdivisions`, ptr, max_subdivisions))
}

Rcpp__integrator__get_relative_accuracy <- function(ptr) {
    .Call(`_testutils_integratecpp_Rcpp__integrator__get_relative_accuracy`, ptr)
}

Rcpp__integrator__set_relative_accuracy <- function(ptr, relative_accuracy) {
    invisible(.Call(`_testutils_integratecpp_Rcpp__integrator__set_relative_accuracy`, ptr, relative_accuracy))
}

Rcpp__integrator__get_absolute_accuracy <- function(ptr) {
    .Call(`_testutils_integratecpp_Rcpp__integrator__get_absolute_accuracy`, ptr)
}

Rcpp__integrator__set_absolute_accuracy <- function(ptr, absolute_accuracy) {
    invisible(.Call(`_testutils_integratecpp_Rcpp__integrator__set_absolute_accuracy`, ptr, absolute_accuracy))
}

Rcpp__integrator__get_work_size <- function(ptr) {
    .Call(`_testutils_integratecpp_Rcpp__integrator__get_work_size`, ptr)
}

Rcpp__integrator__set_work_size <- function(ptr, work_size) {
    invisible(.Call(`_testutils_integratecpp_Rcpp__integrator__set_work_size`, ptr, work_size))
}

Rcpp__integrator__throw_if_invalid <- function(ptr) {
    invisible(.Call(`_testutils_integratecpp_Rcpp__integrator__throw_if_invalid`, ptr))
}

Rcpp__integrator__integrate <- function(ptr, fn, lower, upper) {
    .Call(`_testutils_integratecpp_Rcpp__integrator__integrate`, ptr, fn, lower, upper)
}

